config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'registration' }
  # match 'dashboard' => 'home#dashboard'
  match 'home/dashboard', via: [:get,:post]
  root :to =>'home#index'
  resources :users
  resources :characters
  resources :class_types
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  belongs_to :class_type

  validates :name, :hit_points, :class_type_id, presence: true
  validates :name, length: { minimum: 2, maximum: 20 }

end

app/models/class_type.rb
class ClassType < ApplicationRecord
  has_many :characters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :characters
  has_many :user_characters, through: :characters, source: :user
  # attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :alias

  validates :first_name, :last_name, :alias, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:new, :create]
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]


  def index
    @characters = Character.all
  end

  def show
  end

  def new
    @character = Character.new
  end

  def edit
  end

  def create
    @character = Character.new(character_params)
    @character_class = @character.class_type_id
    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_character
      @character = Character.find(params[:id])
    end

    def character_params
      params.require(:character).permit(:user_id, :name, :hit_points, :class_type_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user= User.new
  end

  def create
    @user = User.new
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.alias = params[:user][:alias]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation =params[:user][:password_confirmation]

    @user.valid?
    if @user.errors.blank?
      @user.save
      redirect_to home_dashboard_path
    else
      render :action => "new"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find( current_user.id )
    @characters = Character.where( user_id: current_user.id )
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update( user_params )
      redirect_to user_path
    else
      redirect_to "/"
    end
  end

  def destroy
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :alias, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/_form.html.erb
<%= form_for(character) do |f| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :class_type_id %>
    <% if @character.class_type %>
      <%= @character.class_type.name %>
    <% else %>
      <%= f.collection_select :class_type_id, ClassType.order(:name), :id, :name, include_blank: true %>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :hit_points %>
    <% if @character.hit_points %>
      <%= @character.hit_points %>
    <% else %>
      <%= f.number_field :hit_points, { id: 'hitbox', class: 'input-box'} %>
      <input id="hit" type="button" value="Roll" onclick="rollhit(),this.style.display='none';">
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', user_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characters</h1>
<p>test hover javascript</p>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Name</th>
      <th>Class</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.user.alias %></td>
        <td><%= character.name %></td>
        <td><%= character.class_type.name %></td>
        <% if character.user.id == current_user.id %>
          <td><%= link_to 'Show', character %></td>
          <td><%= link_to 'Edit', edit_character_path(character) %></td>
          <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td class="gray-text">Not</td>
          <td class="gray-text">Your</td>
          <td class="gray-text">Character</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @character.user.first_name %> <%= @character.user.last_name %> (<%= @character.user.alias %>)
</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Class</th>
      <th>Hit Points</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @character.name %></td>
      <td><%= @character.class_type.name %></td>
      <td><%= @character.hit_points %></td>
    </tr>
  </tbody>
</table>
<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Class:</strong>
  <%= @character.class_type.name %>
</p>

<p>
  <strong>Hit Points:</strong>
  <%= @character.hit_points %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', user_path %>

app/views/home/dashboard.html.erb
<p>hi welcome to this goddamn game. you have successfully registered to your goddamn game account</p>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

app/views/home/index.html.erb
<% if user_signed_in? %>

<h3>You're signed in, <%= current_user.alias %></h3>
<%= link_to "View Account", user_path(current_user.id) %> |
<!-- <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %> -->

<% else %>

<h1> welcome to here, bastard</h1>
<%= link_to "Sign In", new_user_session_path, :method => :get %>
<%= link_to "Sign up", new_user_registration_path, :method => :get %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game Prototype 02</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <h4 class="bordered">
        Online now: <a href="/users/show"><%= current_user.first_name %> <%= current_user.last_name %></a>  |
        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
      </h4>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit User: <%= current_user.alias %></h1>
<%= form_for current_user, :url => { :action => "update"}, method: :patch do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <p>
    First Name: <%= f.text_field :first_name %><br />
  </p>
  <p>
    Last Name: <%= f.text_field :last_name %><br />
  </p>
  <p>
    Alias: <%= f.text_field :alias %><br />
  </p>
  <p>
    Email: <%= f.text_field :email %><br />
  </p>
  <p>
    <%= f.submit "Update User Account" %>
  </p>
  <!-- <a href="/users#index">back</a> -->
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>User Account for <%= @user.first_name %> <%= @user.last_name %></h1>
   user id: <%= @user.id %>
  <p>
    Name: <%= @user.first_name %> <%= @user.last_name %><br />
  </p>
  <p>
    Alias: <%= @user.alias %><br />
  </p>
  <p>
    Email: <%= @user.email %><br />
  </p>
  <%= link_to 'Edit Profile', edit_user_path %> |


<%= link_to 'Create Character', new_character_path %> | <%= link_to 'View All Characters', characters_path %>
  <table>
    <caption><h3>Your Character(s)</h3></caption>
    <thead>
      <tr>
        <th>Owner</th>
        <th>Name</th>
        <th>Hit Points</th>
        <th>Class</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @characters.each do |character| %>
        <tr>
          <td><%= character.user.first_name %> <%= character.user.last_name %></td>
          <td><%= character.name %></td>
          <td><%= character.hit_points %></td>
          <td><%= character.class_type.name %>
          <td><%= link_to 'Show', character %></td>
          <td><%= link_to 'Edit', edit_character_path(character) %></td>
          <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>